on: push
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        env:
          SUPER_SECRET: ${{secrets.SUPER_SECRET}}
        with:
          script: |
            console.info(process.env.SUPER_SECRET);
            console.info(Buffer.from(process.env.SUPER_SECRET, 'utf8').toString('base64'));
